# ============================================
# TEMPLATE - This file is auto-generated by the
# GitHub Action workflow on each release.
# ============================================

cask "gearsystem" do
  arch arm: "arm64", intel: "intel"

  version "3.5.0"
  sha256 arm:   "PLACEHOLDER_ARM64_SHA256",
         intel: "PLACEHOLDER_INTEL_SHA256"

  url "https://github.com/drhelius/Gearsystem/releases/download/#{version}/Gearsystem-#{version}-desktop-macos-#{arch}.zip"
  name "Gearsystem"
  desc "Sega Master System / Game Gear / SG-1000 emulator"
  homepage "https://github.com/drhelius/Gearsystem"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: ">= :monterey"

  app "Gearsystem.app"

  zap trash: [
    "~/Library/Preferences/com.geardome.gearsystem.plist",
    "~/Library/Application Support/gearsystem",
  ]
end
