# ============================================
# TEMPLATE - This file is auto-generated by the
# GitHub Action workflow on each release.
# ============================================

cask "gearboy" do
  arch arm: "arm64", intel: "intel"

  version "3.5.0"
  sha256 arm:   "PLACEHOLDER_ARM64_SHA256",
         intel: "PLACEHOLDER_INTEL_SHA256"

  url "https://github.com/drhelius/Gearboy/releases/download/#{version}/Gearboy-#{version}-desktop-macos-#{arch}.zip"
  name "Gearboy"
  desc "Game Boy / Game Boy Color emulator"
  homepage "https://github.com/drhelius/Gearboy"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: ">= :monterey"

  app "Gearboy.app"

  zap trash: [
    "~/Library/Preferences/com.geardome.gearboy.plist",
    "~/Library/Application Support/gearboy",
  ]
end
