# ============================================
# TEMPLATE - This file is auto-generated by the
# GitHub Action workflow on each release.
# ============================================

cask "gearlynx" do
  arch arm: "arm64", intel: "intel"

  version "1.0.0"
  sha256 arm:   "PLACEHOLDER_ARM64_SHA256",
         intel: "PLACEHOLDER_INTEL_SHA256"

  url "https://github.com/drhelius/Gearlynx/releases/download/#{version}/Gearlynx-#{version}-desktop-macos-#{arch}.zip"
  name "Gearlynx"
  desc "Atari Lynx emulator"
  homepage "https://github.com/drhelius/Gearlynx"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: ">= :monterey"

  app "Gearlynx.app"

  zap trash: [
    "~/Library/Preferences/com.geardome.gearlynx.plist",
    "~/Library/Application Support/gearlynx",
  ]
end
