# ============================================
# TEMPLATE - This file is auto-generated by the
# GitHub Action workflow on each release.
# ============================================

cask "geargrafx" do
  arch arm: "arm64", intel: "intel"

  version "1.6.12"
  sha256 arm:   "PLACEHOLDER_ARM64_SHA256",
         intel: "PLACEHOLDER_INTEL_SHA256"

  url "https://github.com/drhelius/Geargrafx/releases/download/#{version}/Geargrafx-#{version}-desktop-macos-#{arch}.zip"
  name "Geargrafx"
  desc "TurboGrafx-16 / PC Engine / SuperGrafx / PCE CD-ROM² emulator"
  homepage "https://github.com/drhelius/Geargrafx"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: ">= :monterey"

  app "Geargrafx.app"

  zap trash: [
    "~/Library/Preferences/com.geardome.geargrafx.plist",
    "~/Library/Application Support/geargrafx",
  ]
end
