# ============================================
# TEMPLATE - This file is auto-generated by the
# GitHub Action workflow on each release.
# ============================================

cask "gearcoleco" do
  arch arm: "arm64", intel: "intel"

  version "1.1.0"
  sha256 arm:   "PLACEHOLDER_ARM64_SHA256",
         intel: "PLACEHOLDER_INTEL_SHA256"

  url "https://github.com/drhelius/Gearcoleco/releases/download/#{version}/Gearcoleco-#{version}-desktop-macos-#{arch}.zip"
  name "Gearcoleco"
  desc "ColecoVision emulator"
  homepage "https://github.com/drhelius/Gearcoleco"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: ">= :monterey"

  app "Gearcoleco.app"

  zap trash: [
    "~/Library/Preferences/com.geardome.gearcoleco.plist",
    "~/Library/Application Support/gearcoleco",
  ]
end
